server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/shop?useUnicode=true&characterEncoding=UTF-8&timezone=UT+8:00
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      min-idle: 5
      max-idle: 10
      initial-size: 5
      max-wait-millis: 10000
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
#    properties:
#      hibernate:
#        jdbc:
#         batch_size: 20
#         order_inserts: true
#         order_updates: true
#         batch_versioned_data: true





